CREATE TABLE network_documents (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Documentação de infraestrutura',
    responsible TEXT NOT NULL DEFAULT '',
    general_description TEXT NOT NULL DEFAULT '',
    internet_wan TEXT NOT NULL DEFAULT '',
    lan TEXT NOT NULL DEFAULT '',
    vlans TEXT NOT NULL DEFAULT '',
    wifi TEXT NOT NULL DEFAULT '',
    cctv TEXT NOT NULL DEFAULT '',
    telephony TEXT NOT NULL DEFAULT '',
    servers TEXT NOT NULL DEFAULT '',
    racks TEXT NOT NULL DEFAULT '',
    cabling TEXT NOT NULL DEFAULT '',
    fiber TEXT NOT NULL DEFAULT '',
    links TEXT NOT NULL DEFAULT '',
    power TEXT NOT NULL DEFAULT '',
    procedures TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    free_text TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
