import { FormEvent, useEffect, useState } from 'react'
import { api, items, json } from '../api'
import { Client, Project } from '../types'
import { ConfirmButton, Empty, Field, Modal, Notice, PageHeader, Panel } from '../components'

const emptyClient:Client={id:'',name:'',legalName:'',document:'',phone:'',email:'',contactName:'',address:'',city:'',state:'',postalCode:'',description:'',notes:''}
const emptyProject:Project={id:'',clientId:'',name:'',description:'',location:'',address:'',localContact:'',notes:''}

export default function ClientsPage({onOpenVisits}:{onOpenVisits?:(projectId:string)=>void}) {
  const [clients,setClients]=useState<Client[]>([])
  const [selected,setSelected]=useState<Client>()
  const [projects,setProjects]=useState<Project[]>([])
  const [query,setQuery]=useState('')
  const [clientForm,setClientForm]=useState<Client>()
  const [projectForm,setProjectForm]=useState<Project>()
  const [message,setMessage]=useState('')
  const loadClients=async()=>{try{setClients(items(await api<{items:Client[]}>(`/clients?q=${encodeURIComponent(query)}`)))}catch(error){setMessage(String(error))}}
  const select=async(client:Client)=>{setSelected(client);setProjects(items(await api<{items:Project[]}>(`/clients/${client.id}/projects`)))}
  useEffect(()=>{void loadClients()},[])
  const saveClient=async(event:FormEvent)=>{event.preventDefault();if(!clientForm)return;const saved=clientForm.id?await api<Client>(`/clients/${clientForm.id}`,json('PUT',clientForm)):await api<Client>('/clients',json('POST',clientForm));setClientForm(undefined);setMessage('Cliente salvo.');await loadClients();await select(saved)}
  const saveProject=async(event:FormEvent)=>{event.preventDefault();if(!projectForm||!selected)return;if(projectForm.id){await api<Project>(`/projects/${projectForm.id}`,json('PUT',projectForm))}else{await api<Project>(`/clients/${selected.id}/projects`,json('POST',projectForm))};setProjectForm(undefined);setMessage('Projeto salvo.');await select(selected)}
  const deleteClient=async()=>{if(!selected)return;await api(`/clients/${selected.id}`,{method:'DELETE'});setSelected(undefined);setProjects([]);setMessage('Cliente excluído.');await loadClients()}
  const deleteProject=async(id:string)=>{await api(`/projects/${id}`,{method:'DELETE'});if(selected)await select(selected)}
  return <>
    <PageHeader eyebrow="CADASTROS" title="Clientes e projetos" description="Organize cada instalação dentro de seu cliente." actions={<button className="primary" onClick={()=>setClientForm({...emptyClient})}>+ Novo cliente</button>}/>
    <Notice message={message} onClose={()=>setMessage('')}/>
    <div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void loadClients()} placeholder="Nome, documento ou e-mail"/><button onClick={()=>void loadClients()}>Pesquisar</button></div>
    <div className="split">
      <Panel title={`Clientes (${clients.length})`} className="list-panel">{clients.length===0?<Empty>Nenhum cliente encontrado.</Empty>:<div className="select-list">{clients.map(client=><button className={selected?.id===client.id?'selected':''} key={client.id} onClick={()=>void select(client)}><b>{client.name}</b><span>{client.city||client.email||'Sem detalhes'}</span></button>)}</div>}</Panel>
      <Panel title={selected?.name??'Detalhes'} actions={selected&&<><button onClick={()=>setClientForm({...selected})}>Editar cliente</button><ConfirmButton message="Excluir cliente e todos os projetos relacionados?" onConfirm={()=>void deleteClient()}>Excluir</ConfirmButton></>}>
        {!selected?<Empty>Selecione um cliente.</Empty>:<><dl className="details"><dt>Razão social</dt><dd>{selected.legalName||'—'}</dd><dt>Contato</dt><dd>{selected.contactName||selected.email||selected.phone||'—'}</dd><dt>Endereço</dt><dd>{[selected.address,selected.city,selected.state].filter(Boolean).join(', ')||'—'}</dd></dl><div className="section-heading"><h3>Projetos</h3><button onClick={()=>setProjectForm({...emptyProject,clientId:selected.id})}>+ Novo projeto</button></div>{projects.length===0?<Empty>Nenhum projeto cadastrado.</Empty>:<div className="table-scroll"><table><thead><tr><th>Nome</th><th>Localização</th><th>Contato</th><th></th></tr></thead><tbody>{projects.map(project=><tr key={project.id}><td><b>{project.name}</b></td><td>{project.location||'—'}</td><td>{project.localContact||'—'}</td><td className="row-actions"><button onClick={()=>onOpenVisits?.(project.id)}>Visitas</button><button onClick={()=>setProjectForm({...project})}>Editar</button><ConfirmButton message="Excluir este projeto?" onConfirm={()=>void deleteProject(project.id)}>Excluir</ConfirmButton></td></tr>)}</tbody></table></div>}</>}
      </Panel>
    </div>
    {clientForm&&<Modal title={clientForm.id?'Editar cliente':'Novo cliente'} onClose={()=>setClientForm(undefined)} wide><form onSubmit={saveClient} className="form-grid"><Field label="Nome *"><input required value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/></Field><Field label="Razão social"><input value={clientForm.legalName} onChange={e=>setClientForm({...clientForm,legalName:e.target.value})}/></Field><Field label="Documento"><input value={clientForm.document} onChange={e=>setClientForm({...clientForm,document:e.target.value})}/></Field><Field label="Responsável"><input value={clientForm.contactName} onChange={e=>setClientForm({...clientForm,contactName:e.target.value})}/></Field><Field label="E-mail"><input type="email" value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})}/></Field><Field label="Telefone"><input value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/></Field><Field label="Endereço"><input value={clientForm.address} onChange={e=>setClientForm({...clientForm,address:e.target.value})}/></Field><Field label="Cidade"><input value={clientForm.city} onChange={e=>setClientForm({...clientForm,city:e.target.value})}/></Field><Field label="Estado"><input maxLength={2} value={clientForm.state} onChange={e=>setClientForm({...clientForm,state:e.target.value})}/></Field><Field label="CEP"><input value={clientForm.postalCode} onChange={e=>setClientForm({...clientForm,postalCode:e.target.value})}/></Field><Field label="Observações"><textarea value={clientForm.notes} onChange={e=>setClientForm({...clientForm,notes:e.target.value})}/></Field><div className="form-actions"><button type="button" onClick={()=>setClientForm(undefined)}>Cancelar</button><button className="primary">Salvar</button></div></form></Modal>}
    {projectForm&&<Modal title={projectForm.id?'Editar projeto':'Novo projeto'} onClose={()=>setProjectForm(undefined)}><form onSubmit={saveProject} className="form-grid one"><Field label="Nome *"><input required value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})}/></Field><Field label="Localização"><input value={projectForm.location} onChange={e=>setProjectForm({...projectForm,location:e.target.value})}/></Field><Field label="Endereço"><input value={projectForm.address} onChange={e=>setProjectForm({...projectForm,address:e.target.value})}/></Field><Field label="Contato local"><input value={projectForm.localContact} onChange={e=>setProjectForm({...projectForm,localContact:e.target.value})}/></Field><Field label="Descrição"><textarea value={projectForm.description} onChange={e=>setProjectForm({...projectForm,description:e.target.value})}/></Field><div className="form-actions"><button type="button" onClick={()=>setProjectForm(undefined)}>Cancelar</button><button className="primary">Salvar</button></div></form></Modal>}
  </>
}
