import { FormEvent, useEffect, useRef, useState } from 'react'
import { api, items, json } from '../api'
import { Project, Scan, ScanChange, ScanHost } from '../types'
import { Empty, Notice, PageHeader, Panel, Status } from '../components'

type Progress = { scanId:string; status:string; hostsScanned:number; hostsFound:number; total:number; host?:ScanHost }

export default function ScannerPage(){
  const [projects,setProjects]=useState<Project[]>([]);const [project,setProject]=useState('');const [network,setNetwork]=useState('192.168.0.0/24');const [scans,setScans]=useState<Scan[]>([]);const [selected,setSelected]=useState<Scan>();const [hosts,setHosts]=useState<ScanHost[]>([]);const [changes,setChanges]=useState<ScanChange[]>([]);const [progress,setProgress]=useState<Progress>();const [message,setMessage]=useState('');const stream=useRef<EventSource|undefined>(undefined)
  const loadScans=async()=>setScans(items(await api<{items:Scan[]}>(`/scans?project_id=${project}`)))
  const loadResult=async(scan:Scan)=>{setSelected(scan);const [hostValue,changeValue,fresh]=await Promise.all([api<{items:ScanHost[]}>(`/scans/${scan.id}/hosts`),api<{items:ScanChange[]}>(`/scans/${scan.id}/changes`),api<Scan>(`/scans/${scan.id}`)]);setHosts(items(hostValue));setChanges(items(changeValue));setSelected(fresh)}
  useEffect(()=>{void api<{items:Project[]}>('/projects').then(v=>setProjects(items(v)));return()=>stream.current?.close()},[])
  useEffect(()=>{void loadScans()},[project])
  const start=async(event:FormEvent)=>{event.preventDefault();const scan=await api<Scan>('/scans',json('POST',{projectId:project,network}));setSelected(scan);setHosts([]);setChanges([]);setProgress({scanId:scan.id,status:'queued',hostsScanned:0,hostsFound:0,total:0});await loadScans();stream.current?.close();const source=new EventSource(`/api/v1/scans/${scan.id}/events`);stream.current=source;source.addEventListener('progress',raw=>{const value=JSON.parse((raw as MessageEvent).data) as Progress;setProgress(value);if(value.host?.status==='online')setHosts(current=>current.some(item=>item.ip===value.host?.ip)?current:[...current,value.host!]);if(value.status!=='running'){source.close();void loadScans();void loadResult({...scan,status:value.status})}});source.onerror=()=>{source.close();void loadScans()}}
  const cancel=async()=>{if(!selected)return;await api(`/scans/${selected.id}/cancel`,{method:'POST'});setMessage('Cancelamento solicitado.')}
  const addDevice=async(host:ScanHost)=>{if(!selected)return;const name=prompt('Nome do equipamento',host.hostname||`${host.deviceType||'Dispositivo'} ${host.ip}`);if(!name)return;const device=await api<{id:string}>('/devices',json('POST',{projectId:selected.projectId,name,categoryId:'other',manufacturer:host.manufacturer,hostname:host.hostname,status:'online'}));await api(`/devices/${device.id}/addresses`,json('POST',{type:'ipv4',address:host.ip,primary:true}));if(host.mac)await api(`/devices/${device.id}/addresses`,json('POST',{type:'mac',address:host.mac,primary:true}));setMessage('Host adicionado ao inventário.')}
  const percentage=progress?.total?Math.round(progress.hostsScanned/progress.total*100):0
  return <><PageHeader eyebrow="DESCOBERTA" title="Scanner de rede" description="Descoberta controlada em redes autorizadas com progresso em tempo real."/><div className="warning">⚠ Utilize o scanner somente em redes e equipamentos para os quais você possui autorização.</div><Notice message={message} onClose={()=>setMessage('')}/><Panel title="Novo scan"><form className="scan-form" onSubmit={start}><select required value={project} onChange={e=>setProject(e.target.value)}><option value="">Selecione o projeto</option>{projects.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select><input required value={network} onChange={e=>setNetwork(e.target.value)} placeholder="192.168.0.0/24 ou 192.168.0.1-192.168.0.254"/><button className="primary">Iniciar descoberta</button></form>{progress&&['queued','running'].includes(progress.status)&&<div className="progress-card"><div><b>Escaneando {network}</b><Status value={progress.status}/></div><progress max={100} value={percentage}/><div><span>{progress.hostsScanned} / {progress.total} hosts</span><span>Encontrados: {progress.hostsFound}</span><button className="danger" onClick={()=>void cancel()}>Cancelar scan</button></div></div>}</Panel><div className="split scanner-split"><Panel title="Histórico"><div className="select-list">{scans.length===0?<Empty>Nenhum scan realizado.</Empty>:scans.map(scan=><button className={selected?.id===scan.id?'selected':''} key={scan.id} onClick={()=>void loadResult(scan)}><div><b>{scan.network}</b><Status value={scan.status}/></div><span>{scan.hostsFound} encontrados · {scan.hostsScanned} verificados</span></button>)}</div></Panel><Panel title={selected?`Resultados · ${selected.network}`:'Resultados'}>{!selected?<Empty>Selecione ou inicie um scan.</Empty>:<><div className="tabs-summary"><span><b>{hosts.length}</b> hosts encontrados</span><span><b>{changes.length}</b> alterações</span></div>{hosts.length>0&&<div className="table-scroll"><table><thead><tr><th>IP / hostname</th><th>Identificação</th><th>Métodos</th><th>Confiança</th><th></th></tr></thead><tbody>{hosts.map(host=><tr key={host.ip}><td><code>{host.ip}</code><small>{host.hostname}</small></td><td>{host.deviceType||'Dispositivo'}<small>{host.manufacturer}</small></td><td>{(host.discoveryMethods||[]).join(', ')}</td><td>{Math.round(host.confidence*100)}%<details><summary>Evidências</summary>{host.evidence?.map((evidence,index)=><p key={index}>{evidence.source}: {evidence.detail}</p>)}</details></td><td><button onClick={()=>void addDevice(host)}>Inventariar</button></td></tr>)}</tbody></table></div>}{changes.length>0&&<section><h3>Alterações desde o scan anterior</h3><div className="change-list">{changes.map((change,index)=><div key={index}><b>{change.type||change.Type}</b><span>{change.subject||change.Subject}</span><small>{change.previous||change.Previous} → {change.current||change.Current}</small></div>)}</div></section>}</>}</Panel></div></>
}
