import { ChangeEvent, useEffect, useState } from 'react'
import { api, json } from '../api'
import { Notice, PageHeader, Panel, Status } from '../components'

const labels:Record<string,string>={scan_workers:'Workers do scanner',scan_timeout_ms:'Timeout de conexão (ms)',default_ports:'Portas padrão',upload_limit_mb:'Limite de upload (MB)'}
const defaults:Record<string,string>={scan_workers:'32',scan_timeout_ms:'750',default_ports:'22,80,443,554,8000,8080,8443,8554,37777',upload_limit_mb:'20'}
const operationalKeys=Object.keys(defaults)

export default function SettingsPage({theme,onTheme}:{theme:string;onTheme:(value:string)=>void}){
  const[settings,setSettings]=useState<Record<string,string>>(defaults)
  const[technician,setTechnician]=useState(localStorage.getItem('telecom-technician')||'')
  const[status,setStatus]=useState<{scannerNative:string;nmap:string}>({scannerNative:'available',nmap:'not_installed'})
  const[message,setMessage]=useState('')
  useEffect(()=>{void Promise.all([api<Record<string,string>>('/settings').then(value=>{setSettings({...defaults,...value});if(value.default_technician){setTechnician(value.default_technician);localStorage.setItem('telecom-technician',value.default_technician)}}),api<typeof status>('/system/status').then(setStatus)])},[])
  const save=async(key:string,value:string)=>{try{await api(`/settings/${key}`,json('PUT',{value}));setSettings(current=>({...current,[key]:value}));if(key==='default_technician'){setTechnician(value);localStorage.setItem('telecom-technician',value)}setMessage('Configuração salva.')}catch(error){setMessage(String(error))}}
  const importOUI=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const result=await api<{imported:number}>('/oui/import',{method:'POST',headers:{'Content-Type':'text/csv'},body:await file.text()});setMessage(`${result.imported} prefixos de fabricantes importados com sucesso.`)}catch(error){setMessage(String(error))}}
  return <><PageHeader eyebrow="SISTEMA" title="Configurações" description="Preferências locais e limites operacionais seguros."/><Notice message={message} onClose={()=>setMessage('')}/><div className="cards two"><Panel title="Perfil do técnico"><label className="field"><span>Nome usado em novas visitas</span><div className="inline-form"><input value={technician} onChange={event=>setTechnician(event.target.value)} placeholder="Nome do técnico responsável"/><button className="primary" onClick={()=>void save('default_technician',technician)}>Salvar perfil</button></div></label></Panel><Panel title="Aparência"><label className="theme-choice"><input type="radio" checked={theme==='dark'} onChange={()=>onTheme('dark')}/> Modo escuro</label><label className="theme-choice"><input type="radio" checked={theme==='light'} onChange={()=>onTheme('light')}/> Modo claro</label></Panel></div><div className="cards two"><Panel title="Estado do sistema"><dl className="details"><dt>Scanner nativo</dt><dd><Status value={status.scannerNative==='available'?'online':'offline'}/></dd><dt>Nmap opcional</dt><dd><Status value={status.nmap==='available'?'online':'unknown'}/></dd><dt>Porta HTTP</dt><dd><code>14000</code></dd><dt>Modo</dt><dd>Local / offline</dd></dl></Panel><Panel title="Scanner e armazenamento"><div className="settings-grid one">{operationalKeys.map(key=><label key={key}><span>{labels[key]}</span><div><input value={settings[key]||''} onChange={e=>setSettings(current=>({...current,[key]:e.target.value}))}/><button onClick={()=>void save(key,settings[key])}>Salvar</button></div></label>)}</div></Panel></div><Panel title="Identificação de fabricantes (Base OUI / MAC)"><p>Envie uma tabela CSV personalizada para reconhecer fabricantes pelo endereço MAC. Formato: <code>prefixo,fabricante</code>.</p><input type="file" accept=".csv,text/csv,text/plain" onChange={e=>void importOUI(e)}/></Panel></>
}
