import { useCallback, useEffect, useRef, useState } from 'react'
import { Background, Connection, Controls, Edge, MiniMap, Node, NodeChange, ReactFlow, ReactFlowProvider, addEdge, applyNodeChanges, getNodesBounds, getViewportForBounds } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'
import { api, items, json } from '../api'
import { Device, Diagram, DiagramEdge, DiagramNode, Project } from '../types'
import { Empty, PageHeader, Panel } from '../components'

type Graph={diagram:Diagram;nodes:DiagramNode[];edges:DiagramEdge[]}
const nodeFrom=(value:DiagramNode,devices:Device[]):Node=>{const device=devices.find(item=>item.id===value.deviceId);return{id:value.id,position:{x:value.x,y:value.y},data:{name:value.label,deviceId:value.deviceId,label:<div><b>{value.label}</b><span>{[device?.manufacturer,device?.model].filter(Boolean).join(' ')||'Equipamento'}</span><small>{device?.status||'desconhecido'}</small></div>},className:'telecom-node',style:{width:value.width||190,height:value.height||76}}}
const edgeFrom=(value:DiagramEdge):Edge=>({id:value.id,source:value.sourceNodeId,target:value.targetNodeId,label:value.name||value.type,data:{record:value},style:{stroke:value.color||'#3b82f6',strokeDasharray:value.lineStyle==='dashed'?'6 4':undefined}})

function Editor(){const[projects,setProjects]=useState<Project[]>([]);const[project,setProject]=useState('');const[diagrams,setDiagrams]=useState<Diagram[]>([]);const[diagram,setDiagram]=useState<Diagram>();const[devices,setDevices]=useState<Device[]>([]);const[nodes,setNodes]=useState<Node[]>([]);const[edges,setEdges]=useState<Edge[]>([]);const canvas=useRef<HTMLDivElement>(null)
  useEffect(()=>{void api<{items:Project[]}>('/projects').then(v=>setProjects(items(v)))},[])
  const loadProject=async(id:string)=>{setProject(id);setDiagram(undefined);setNodes([]);setEdges([]);if(!id){setDiagrams([]);setDevices([]);return}const[d,dv]=await Promise.all([api<{items:Diagram[]}>(`/projects/${id}/diagrams`),api<{items:Device[]}>(`/devices?project_id=${id}`)]);setDiagrams(items(d));setDevices(items(dv))}
  const loadGraph=async(id:string)=>{if(!id){setDiagram(undefined);return}const graph=await api<Graph>(`/diagrams/${id}`);setDiagram(graph.diagram);setNodes(graph.nodes.map(value=>nodeFrom(value,devices)));setEdges(graph.edges.map(edgeFrom))}
  const createDiagram=async()=>{if(!project)return;const name=prompt('Nome do diagrama','Topologia geral');if(!name)return;const saved=await api<Diagram>(`/projects/${project}/diagrams`,json('POST',{name,description:''}));setDiagrams(current=>[...current,saved]);await loadGraph(saved.id)}
  const addDevice=async(device:Device)=>{if(!diagram)return;const saved=await api<DiagramNode>(`/diagrams/${diagram.id}/nodes`,json('POST',{deviceId:device.id,label:device.name,x:80+nodes.length%4*220,y:70+Math.floor(nodes.length/4)*130,width:190,height:76,styleJson:'{}'}));setNodes(current=>[...current,nodeFrom(saved,devices)])}
  const changeNodes=useCallback((changes:NodeChange[])=>setNodes(current=>applyNodeChanges(changes,current)),[])
  const persistNode=async(_:unknown,node:Node)=>{if(!diagram)return;await api(`/diagrams/${diagram.id}/nodes/${node.id}`,json('PUT',{deviceId:String(node.data.deviceId||''),label:extractLabel(node),x:node.position.x,y:node.position.y,width:Number(node.width||190),height:Number(node.height||76),styleJson:'{}'}))}
  const connect=useCallback(async(connection:Connection)=>{if(!diagram||!connection.source||!connection.target)return;const saved=await api<DiagramEdge>(`/diagrams/${diagram.id}/edges`,json('POST',{sourceNodeId:connection.source,targetNodeId:connection.target,name:'Ethernet',type:'Ethernet',color:'#3b82f6',lineStyle:'solid'}));setEdges(current=>addEdge(edgeFrom(saved),current))},[diagram])
  const removeSelected=async()=>{if(!diagram)return;const selectedEdges=edges.filter(value=>value.selected);const selectedNodes=nodes.filter(value=>value.selected);for(const edge of selectedEdges)await api(`/diagrams/${diagram.id}/edges/${edge.id}`,{method:'DELETE'});for(const node of selectedNodes)await api(`/diagrams/${diagram.id}/nodes/${node.id}`,{method:'DELETE'});setEdges(current=>current.filter(value=>!value.selected&&!selectedNodes.some(node=>node.id===value.source||node.id===value.target)));setNodes(current=>current.filter(value=>!value.selected))}
  const autoLayout=async()=>{if(!diagram)return;const arranged=nodes.map((node,index)=>({...node,position:{x:60+(index%4)*230,y:60+Math.floor(index/4)*140}}));setNodes(arranged);await Promise.all(arranged.map(node=>api(`/diagrams/${diagram.id}/nodes/${node.id}`,json('PUT',{deviceId:String(node.data.deviceId||''),label:extractLabel(node),x:node.position.x,y:node.position.y,width:190,height:76,styleJson:'{}'}))))}
  const exportRaster=async(pdf=false)=>{const viewport=canvas.current?.querySelector('.react-flow__viewport') as HTMLElement|null;if(!viewport||nodes.length===0)return;const bounds=getNodesBounds(nodes);const width=1400,height=900;const view=getViewportForBounds(bounds,width,height,.4,2,.12);const data=await toPng(viewport,{backgroundColor:'#f8fafc',pixelRatio:2,width,height,style:{width:`${width}px`,height:`${height}px`,transform:`translate(${view.x}px, ${view.y}px) scale(${view.zoom})`}});if(pdf){const out=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const p=out.getImageProperties(data);const reportWidth=277;out.addImage(data,'PNG',10,10,reportWidth,p.height*reportWidth/p.width);out.save(`${diagram?.name||'topologia'}.pdf`)}else{const link=document.createElement('a');link.download=`${diagram?.name||'topologia'}.png`;link.href=data;link.click()}}
  const editEdge=async(_:unknown,edge:Edge)=>{if(!diagram)return;const record=edge.data?.record as DiagramEdge;const name=prompt('Nome da ligação',record.name||record.type);if(name===null)return;const saved=await api<DiagramEdge>(`/diagrams/${diagram.id}/edges/${edge.id}`,json('PUT',{...record,name}));setEdges(current=>current.map(value=>value.id===edge.id?edgeFrom(saved):value))}
  return <><PageHeader eyebrow="REDE" title="Editor visual de topologia" description="Diagramas persistentes com nodes, ligações, minimapa e snap-to-grid. Duplo clique edita uma ligação." actions={<><button disabled={!diagram} onClick={()=>void autoLayout()}>Organizar</button><button disabled={!diagram} onClick={()=>void removeSelected()}>Remover seleção</button><button disabled={!diagram} onClick={()=>void exportRaster()}>PNG</button><button disabled={!diagram} onClick={()=>void exportRaster(true)}>PDF</button>{diagram&&<a className="button" href={`/api/v1/diagrams/${diagram.id}/export.svg`}>SVG</a>}</>}/><div className="topology-toolbar"><select value={project} onChange={e=>void loadProject(e.target.value)}><option value="">Selecione o projeto</option>{projects.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select><select value={diagram?.id||''} onChange={e=>void loadGraph(e.target.value)}><option value="">Selecione o diagrama</option>{diagrams.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select><button disabled={!project} onClick={()=>void createDiagram()}>+ Diagrama</button></div><div className="topology-layout"><Panel title="Equipamentos"><div className="device-palette">{devices.map(device=><button key={device.id} disabled={!diagram||nodes.some(node=>extractLabel(node)===device.name)} onClick={()=>void addDevice(device)}><b>{device.name}</b><span>{device.manufacturer||device.categoryId}</span></button>)}</div></Panel><Panel className="topology-panel">{!diagram?<Empty>Selecione ou crie um diagrama.</Empty>:<div className="flow-canvas" ref={canvas}><ReactFlow nodes={nodes} edges={edges} onNodesChange={changeNodes} onEdgesChange={changes=>setEdges(current=>changes.reduce((result,change)=>change.type==='select'?result.map(edge=>edge.id===change.id?{...edge,selected:change.selected}:edge):result,current))} onNodeDragStop={(event,node)=>void persistNode(event,node)} onEdgeDoubleClick={(event,edge)=>void editEdge(event,edge)} onConnect={connection=>void connect(connection)} deleteKeyCode={null} fitView snapToGrid snapGrid={[20,20]}><Background gap={20}/><MiniMap/><Controls/></ReactFlow></div>}</Panel></div></>
}
function extractLabel(node:Node){return String(node.data.name||'Equipamento')}
export default function TopologyPage(){return <ReactFlowProvider><Editor/></ReactFlowProvider>}
