import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ApiError, api, items, json, localDateTime } from '../api'
import { Client, Project, TechnicalVisit, VisitChecklistItem, VisitDeviceItem, VisitPendingItem, VisitServiceItem } from '../types'
import { ConfirmButton, Empty, Field, Modal, Notice, PageHeader, Panel, Status } from '../components'
import VisitDetails, { DetailSection } from './VisitDetails'
import VisitEvidence from './VisitEvidence'
import { resultLabels, visitTypeLabels } from './visitOptions'

export { resultLabels, visitTypeLabels }
const statusLabels:Record<string,string>={draft:'Rascunho',scheduled:'Agendada',in_progress:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}
type Section='attendance'|'report'|'evidence'|'notes'|DetailSection
type FormError={message:string;field?:string}
const sections:Section[]=['attendance','report','devices','services','checklist','materials','pending','evidence','notes']
const draftKey=(id='new')=>`telecom-visit-draft:${id}`

const emptyVisit=(projectId=''):TechnicalVisit=>({id:'',projectId,clientId:'',clientName:'',projectName:'',protocol:'',title:'',visitType:'corrective_maintenance',status:'draft',result:'',scheduledAt:localDateTime(),startedAt:'',finishedAt:'',durationMinutes:0,responsibleTechnician:localStorage.getItem('telecom-technician')||'',requester:'',localContact:'',requestDescription:'',initialSituation:'',diagnosis:'',workSummary:'',recommendations:'',pendingSummary:'',customerNotes:'',internalNotes:'',requiresReturn:false,returnReason:'',suggestedReturnAt:'',createdAt:'',updatedAt:''})
const displayDate=(value:string)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—'
const calculatedDuration=(visit:TechnicalVisit)=>{if(!visit.startedAt||!visit.finishedAt)return visit.durationMinutes;const minutes=Math.max(0,Math.round((new Date(visit.finishedAt).getTime()-new Date(visit.startedAt).getTime())/60000));return minutes}
const duration=(minutes:number)=>minutes?`${Math.floor(minutes/60)}h${String(minutes%60).padStart(2,'0')}`:'—'

export default function VisitsPage({initialProjectId='',initialVisitId='' }:{initialProjectId?:string;initialVisitId?:string}) {
  const [visits,setVisits]=useState<TechnicalVisit[]>([])
  const [clients,setClients]=useState<Client[]>([])
  const [projects,setProjects]=useState<Project[]>([])
  const [form,setForm]=useState<TechnicalVisit>()
  const [section,setSection]=useState<Section>('attendance')
  const [message,setMessage]=useState('')
  const [formMessage,setFormMessage]=useState('')
  const [formError,setFormError]=useState<FormError>()
  const [saving,setSaving]=useState(false)
  const baseline=useRef('')
  const openedTarget=useRef('')
  const [filters,setFilters]=useState({q:'',clientId:'',projectId:initialProjectId,status:'',result:'',dateFrom:'',dateTo:''})
  const availableProjects=useMemo(()=>filters.clientId?projects.filter(project=>project.clientId===filters.clientId):projects,[projects,filters.clientId])
  const formProjects=useMemo(()=>form?.clientId?projects.filter(project=>project.clientId===form.clientId):projects,[projects,form?.clientId])
  const dirty=Boolean(form&&JSON.stringify(form)!==baseline.current)

  const load=async(next=filters)=>{const params=new URLSearchParams();if(next.q)params.set('q',next.q);if(next.clientId)params.set('client_id',next.clientId);if(next.projectId)params.set('project_id',next.projectId);if(next.status)params.set('status',next.status);if(next.result)params.set('result',next.result);if(next.dateFrom)params.set('date_from',next.dateFrom);if(next.dateTo)params.set('date_to',next.dateTo);try{setVisits(items(await api<{items:TechnicalVisit[]}>(`/technical-visits?${params}`)))}catch(error){setMessage(String(error))}}
  useEffect(()=>{void Promise.all([api<{items:Client[]}>('/clients').then(value=>setClients(items(value))),api<{items:Project[]}>('/projects').then(value=>setProjects(items(value)))])},[])
  useEffect(()=>{const next={...filters,projectId:initialProjectId};setFilters(next);void load(next)},[initialProjectId])
  useEffect(()=>{if(!initialVisitId||openedTarget.current===initialVisitId)return;openedTarget.current=initialVisitId;if(initialVisitId==='new'){newVisit();return}void api<TechnicalVisit>(`/technical-visits/${initialVisitId}`).then(edit).catch(error=>setMessage(String(error)))},[initialVisitId])
  useEffect(()=>{if(form&&JSON.stringify(form)!==baseline.current)localStorage.setItem(draftKey(form.id||'new'),JSON.stringify(form))},[form])
  useEffect(()=>{if(form&&!form.id&&form.projectId&&!form.clientId){const project=projects.find(value=>value.id===form.projectId);if(project)setForm({...form,clientId:project.clientId,localContact:form.localContact||project.localContact||''})}},[projects,form?.projectId])

  const openForm=(visit:TechnicalVisit,nextSection:Section='attendance')=>{setSection(nextSection);setFormError(undefined);setFormMessage('');baseline.current=JSON.stringify(visit);let restored=visit;try{const local=JSON.parse(localStorage.getItem(draftKey(visit.id))||'null') as TechnicalVisit|null;if(local?.updatedAt===visit.updatedAt&&JSON.stringify(local)!==baseline.current){restored=local;setFormMessage('Alterações locais não salvas foram recuperadas neste dispositivo.')}}catch{localStorage.removeItem(draftKey(visit.id))}setForm({...restored})}
  const newVisit=()=>{const project=projects.find(value=>value.id===filters.projectId);let visit={...emptyVisit(filters.projectId),clientId:project?.clientId??filters.clientId,localContact:project?.localContact||''};setFormMessage('');try{const stored=JSON.parse(localStorage.getItem(draftKey())||'null') as TechnicalVisit|null;if(stored&&!stored.id&&(!filters.projectId||stored.projectId===filters.projectId)){visit=stored;setFormMessage('Rascunho não salvo recuperado neste dispositivo.')}}catch{localStorage.removeItem(draftKey())}baseline.current='';setSection('attendance');setFormError(undefined);setForm(visit)}
  const edit=(visit:TechnicalVisit)=>openForm(visit)
  const save=async(close=false)=>{if(!form)return;setSaving(true);setFormError(undefined);try{const previousID=form.id;const saved=form.id?await api<TechnicalVisit>(`/technical-visits/${form.id}`,json('PUT',form)):await api<TechnicalVisit>('/technical-visits',json('POST',form));baseline.current=JSON.stringify(saved);setForm(saved);localStorage.removeItem(draftKey(previousID||'new'));localStorage.removeItem(draftKey(saved.id));setFormMessage(form.id?'Alterações salvas.':`${saved.protocol} criada. Continue preenchendo as próximas etapas.`);await load();if(close)setForm(undefined);else if(!form.id)setSection('report')}catch(error){const apiError=error as ApiError;setFormError({message:apiError.message||String(error),field:apiError.field})}finally{setSaving(false)}}
  const submit=(event:FormEvent)=>{event.preventDefault();void save(false)}
  const remove=async(id:string)=>{try{await api(`/technical-visits/${id}`,{method:'DELETE'});setMessage('Visita técnica excluída.');await load()}catch(error){setMessage(String(error))}}
  const duplicateReturn=async(source:TechnicalVisit)=>{try{const created=await api<TechnicalVisit>('/technical-visits',json('POST',{...source,id:'',protocol:'',title:`Retorno — ${source.title}`,status:'scheduled',result:'',scheduledAt:source.suggestedReturnAt||localDateTime(),startedAt:'',finishedAt:'',durationMinutes:0,requestDescription:source.returnReason||source.pendingSummary,diagnosis:'',workSummary:'',customerNotes:'',internalNotes:'',requiresReturn:false,returnReason:'',suggestedReturnAt:'',createdAt:'',updatedAt:''}));const[deviceValue,checklistValue,pendingValue]=await Promise.all([api<{items:VisitDeviceItem[]}>(`/technical-visits/${source.id}/devices`),api<{items:VisitChecklistItem[]}>(`/technical-visits/${source.id}/checklist`),api<{items:VisitPendingItem[]}>(`/technical-visits/${source.id}/pending-items`)]);await Promise.all([...items(deviceValue).map(item=>api(`/technical-visits/${created.id}/devices`,json('POST',{deviceId:item.deviceId,role:item.role,notes:item.notes}))),...items(checklistValue).map(item=>api(`/technical-visits/${created.id}/checklist`,json('POST',{text:item.text,status:'pending',notes:item.notes,order:item.order}))),...items(pendingValue).filter(item=>!['resolved','cancelled'].includes(item.status)).map(item=>api(`/technical-visits/${created.id}/pending-items`,json('POST',{description:item.description,priority:item.priority,responsible:item.responsible,dueAt:item.dueAt,status:'pending'}))) ]);await load();openForm(created);setFormMessage(`${created.protocol} criada com equipamentos, checklist e pendências da visita anterior.`)}catch(error){setMessage(String(error))}}
  const setClient=(clientId:string)=>setForm(form?{...form,clientId,projectId:projects.some(project=>project.id===form.projectId&&project.clientId===clientId)?form.projectId:''}:form)
  const startNow=()=>{if(!form)return;setForm({...form,startedAt:form.startedAt||localDateTime(),status:'in_progress'});setFormMessage('Atendimento iniciado. Salve para registrar o horário.')}
  const finishNow=()=>{if(!form)return;const now=localDateTime();setForm({...form,startedAt:form.startedAt||now,finishedAt:now,status:form.result?'completed':'in_progress'});setSection('notes');if(!form.result)setFormError({field:'result',message:'Selecione o resultado para concluir a visita.'});else setFormMessage('Atendimento concluído. Salve para confirmar.')}
  const generateSummaries=async()=>{if(!form?.id)return;try{const[serviceValue,pendingValue]=await Promise.all([api<{items:VisitServiceItem[]}>(`/technical-visits/${form.id}/services`),api<{items:VisitPendingItem[]}>(`/technical-visits/${form.id}/pending-items`)]);const serviceList=items(serviceValue);const pendingList=items(pendingValue).filter(item=>!['resolved','cancelled'].includes(item.status));setForm({...form,workSummary:serviceList.map(item=>`• ${item.description}${item.deviceName?` — ${item.deviceName}`:''}`).join('\n'),pendingSummary:pendingList.map(item=>`• ${item.description}${item.responsible?` — ${item.responsible}`:''}${item.dueAt?` — até ${new Date(`${item.dueAt}T00:00`).toLocaleDateString('pt-BR')}`:''}`).join('\n')});setFormMessage('Resumos gerados a partir dos serviços e pendências estruturados.')}catch(error){setFormError({message:String(error)})}}
  const fieldError=(field:string)=>formError?.field===field?formError.message:undefined
  const closeForm=()=>{if(!dirty||window.confirm('Existem alterações não salvas. Deseja fechar mesmo assim?'))setForm(undefined)}
  const goNext=()=>{const current=sections.indexOf(section);if(current<sections.length-1){if(!form?.id&&current>=1){setFormMessage('Salve a visita para liberar as etapas estruturadas.');return}setSection(sections[current+1])}}

  return <>
    <PageHeader eyebrow="ATENDIMENTO" title="Visitas técnicas" description="Registre e acompanhe os atendimentos por cliente e projeto." actions={<button className="primary" onClick={newVisit}>+ Nova visita</button>}/>
    <Notice message={message} onClose={()=>setMessage('')}/>
    <Panel className="visit-filters"><div className="filter-grid"><input aria-label="Pesquisar visitas" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} onKeyDown={e=>e.key==='Enter'&&void load()} placeholder="Protocolo, título, técnico ou diagnóstico"/><select aria-label="Filtrar cliente" value={filters.clientId} onChange={e=>setFilters({...filters,clientId:e.target.value,projectId:''})}><option value="">Todos os clientes</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><select aria-label="Filtrar projeto" value={filters.projectId} onChange={e=>setFilters({...filters,projectId:e.target.value})}><option value="">Todos os projetos</option>{availableProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><select aria-label="Filtrar status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar resultado" value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}><option value="">Todos os resultados</option>{Object.entries(resultLabels).filter(([value])=>value).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Field label="De"><input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/></Field><Field label="Até"><input type="date" value={filters.dateTo} onChange={e=>setFilters({...filters,dateTo:e.target.value})}/></Field><button onClick={()=>void load()}>Aplicar filtros</button></div></Panel>
    <Panel title={`Visitas (${visits.length})`}>{visits.length===0?<Empty>Nenhuma visita encontrada.</Empty>:<div className="table-scroll responsive-table"><table><thead><tr><th>Protocolo</th><th>Data</th><th>Cliente / Projeto</th><th>Tipo</th><th>Técnico</th><th>Resultado</th><th>Status</th><th></th></tr></thead><tbody>{visits.map(visit=><tr key={visit.id}><td data-label="Protocolo"><button className="link-button" onClick={()=>edit(visit)}>{visit.protocol}</button><small>{visit.title}</small></td><td data-label="Data">{displayDate(visit.scheduledAt)}</td><td data-label="Cliente / Projeto">{visit.clientName}<small>{visit.projectName}</small></td><td data-label="Tipo">{visitTypeLabels[visit.visitType]}</td><td data-label="Técnico">{visit.responsibleTechnician||'—'}</td><td data-label="Resultado">{resultLabels[visit.result]}</td><td data-label="Status"><Status value={visit.status}/>{visit.requiresReturn&&<small className="return-flag">RETORNO NECESSÁRIO</small>}</td><td className="row-actions"><button onClick={()=>edit(visit)}>Abrir</button>{visit.requiresReturn&&<button onClick={()=>void duplicateReturn(visit)}>Criar retorno</button>}<ConfirmButton message={`Excluir ${visit.protocol}?`} onConfirm={()=>void remove(visit.id)}>Excluir</ConfirmButton></td></tr>)}</tbody></table></div>}</Panel>
    {form&&<Modal title={form.id?`${form.protocol} · ${form.title}`:'Nova visita técnica'} onClose={()=>setForm(undefined)} wide confirmClose={dirty}>
      <form onSubmit={submit} className="visit-form">
        {(formMessage||formError)&&<div className={formError?'form-alert error':'form-alert'} role="status"><span>{formError?.message||formMessage}</span>{formError&&<button type="button" onClick={()=>setFormError(undefined)}>×</button>}</div>}
        <div className="visit-quick-actions"><button type="button" onClick={startNow} disabled={form.status==='completed'}>▶ Iniciar agora</button><button type="button" onClick={finishNow} disabled={form.status==='completed'}>✓ Finalizar agora</button><span>{form.startedAt&&`Duração: ${duration(calculatedDuration(form))}`}</span></div>
        <div className="form-tabs" role="tablist">{sections.map((value,index)=><button key={value} type="button" role="tab" aria-selected={section===value} className={section===value?'active':''} disabled={!form.id&&index>=2&&index<=7} onClick={()=>setSection(value)}>{index+1}. {({attendance:'Atendimento',report:'Relato técnico',devices:'Equipamentos',services:'Serviços',checklist:'Checklist',materials:'Materiais',pending:'Pendências',evidence:'Evidências',notes:'Resultado'} as Record<Section,string>)[value]}</button>)}</div>
        {section==='attendance'&&<div className="form-grid"><Field label="Cliente *" error={fieldError('clientId')}><select required value={form.clientId} onChange={e=>setClient(e.target.value)}><option value="">Selecione</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Projeto *" error={fieldError('projectId')}><select required value={form.projectId} onChange={e=>{const project=projects.find(value=>value.id===e.target.value);setForm({...form,projectId:e.target.value,localContact:form.localContact||project?.localContact||''})}}><option value="">Selecione</option>{formProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><Field label="Título *" error={fieldError('title')}><input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Tipo de atendimento *" error={fieldError('visitType')}><select required value={form.visitType} onChange={e=>setForm({...form,visitType:e.target.value})}>{Object.entries(visitTypeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Data e hora *" error={fieldError('scheduledAt')}><input required type="datetime-local" value={form.scheduledAt.slice(0,16)} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></Field><Field label="Status" error={fieldError('status')}><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Início" error={fieldError('startedAt')}><input type="datetime-local" value={form.startedAt.slice(0,16)} onChange={e=>setForm({...form,startedAt:e.target.value})}/></Field><Field label="Fim" error={fieldError('finishedAt')}><input type="datetime-local" value={form.finishedAt.slice(0,16)} onChange={e=>setForm({...form,finishedAt:e.target.value})}/></Field><Field label="Técnico responsável"><input value={form.responsibleTechnician} onChange={e=>setForm({...form,responsibleTechnician:e.target.value})}/></Field><Field label="Duração calculada"><input readOnly value={duration(calculatedDuration(form))}/></Field><Field label="Solicitante"><input value={form.requester} onChange={e=>setForm({...form,requester:e.target.value})}/></Field><Field label="Contato no local"><input value={form.localContact} onChange={e=>setForm({...form,localContact:e.target.value})}/></Field></div>}
        {section==='report'&&<div className="form-grid one"><div className="section-toolbar"><span>Os resumos podem ser gerados dos itens estruturados.</span><button type="button" disabled={!form.id} onClick={()=>void generateSummaries()}>Gerar resumos</button></div><Field label="Descrição da solicitação"><textarea value={form.requestDescription} onChange={e=>setForm({...form,requestDescription:e.target.value})}/></Field><Field label="Situação encontrada"><textarea value={form.initialSituation} onChange={e=>setForm({...form,initialSituation:e.target.value})}/></Field><Field label="Diagnóstico"><textarea value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})}/></Field><Field label="Resumo dos serviços executados"><textarea value={form.workSummary} onChange={e=>setForm({...form,workSummary:e.target.value})}/></Field><Field label="Recomendações"><textarea value={form.recommendations} onChange={e=>setForm({...form,recommendations:e.target.value})}/></Field><Field label="Resumo de pendências"><textarea value={form.pendingSummary} onChange={e=>setForm({...form,pendingSummary:e.target.value})}/></Field></div>}
        {section==='notes'&&<div className="form-grid"><Field label="Resultado" error={fieldError('result')}><select value={form.result} onChange={e=>setForm({...form,result:e.target.value,status:form.finishedAt&&e.target.value?'completed':form.status})}>{Object.entries(resultLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Necessita retorno"><select value={form.requiresReturn?'yes':'no'} onChange={e=>setForm({...form,requiresReturn:e.target.value==='yes'})}><option value="no">Não</option><option value="yes">Sim</option></select></Field>{form.requiresReturn&&<><Field label="Motivo do retorno"><input value={form.returnReason} onChange={e=>setForm({...form,returnReason:e.target.value})}/></Field><Field label="Data sugerida"><input type="datetime-local" value={form.suggestedReturnAt.slice(0,16)} onChange={e=>setForm({...form,suggestedReturnAt:e.target.value})}/></Field></>}<Field label="Observações para o cliente"><textarea value={form.customerNotes} onChange={e=>setForm({...form,customerNotes:e.target.value})}/></Field><Field label="Observações internas (não públicas)"><textarea value={form.internalNotes} onChange={e=>setForm({...form,internalNotes:e.target.value})}/></Field></div>}
        {form.id&&(['devices','services','checklist','materials','pending'] as DetailSection[]).includes(section as DetailSection)&&<VisitDetails visit={form} section={section as DetailSection} onMessage={value=>{setFormMessage(value);setFormError(undefined)}}/>}
        {form.id&&section==='evidence'&&<VisitEvidence visit={form} onMessage={value=>{setFormMessage(value);setFormError(undefined)}}/>}
        <div className="form-actions sticky-actions"><button type="button" onClick={closeForm}>Fechar</button><button type="button" disabled={saving||!dirty} onClick={()=>void save(true)}>Salvar e fechar</button>{section!=='notes'&&<button type="button" onClick={goNext}>Próxima etapa</button>}<button disabled={saving||!dirty} className="primary">{saving?'Salvando…':'Salvar'}</button></div>
      </form>
    </Modal>}
  </>
}
