import { ReactNode, useEffect, useState } from 'react'
import { api, items, json } from '../api'
import { Device, TechnicalVisit, VisitChecklistItem, VisitDeviceItem, VisitMaterialItem, VisitPendingItem, VisitServiceItem } from '../types'
import { ConfirmButton, Empty, Field } from '../components'

export type DetailSection='devices'|'services'|'checklist'|'materials'|'pending'
type Props={visit:TechnicalVisit;section:DetailSection;onMessage:(message:string)=>void}
const base={id:'',technicalVisitId:'',createdAt:'',updatedAt:''}
const deviceRoles:Record<string,string>={inspected:'Inspecionado',configured:'Configurado',installed:'Instalado',removed:'Removido',replaced:'Substituído',defective:'Defeituoso',tested:'Testado',updated:'Atualizado'}
const priorities:Record<string,string>={low:'Baixa',normal:'Normal',high:'Alta',critical:'Crítica'}
const pendingStatuses:Record<string,string>={pending:'Pendente',in_progress:'Em andamento',resolved:'Resolvida',cancelled:'Cancelada'}

export default function VisitDetails({visit,section,onMessage}:Props){
  if(section==='devices')return <Devices visit={visit} onMessage={onMessage}/>
  if(section==='services')return <Services visit={visit} onMessage={onMessage}/>
  if(section==='checklist')return <Checklist visit={visit} onMessage={onMessage}/>
  if(section==='materials')return <Materials visit={visit} onMessage={onMessage}/>
  return <Pending visit={visit} onMessage={onMessage}/>
}

function Devices({visit,onMessage}:Omit<Props,'section'>){const[list,setList]=useState<VisitDeviceItem[]>([]);const[devices,setDevices]=useState<Device[]>([]);const[draft,setDraft]=useState<VisitDeviceItem>();const load=async()=>{setList(items(await api<{items:VisitDeviceItem[]}>(`/technical-visits/${visit.id}/devices`)));setDevices(items(await api<{items:Device[]}>(`/devices?project_id=${visit.projectId}`)))};useEffect(()=>{void load().catch(error=>onMessage(String(error)))},[visit.id]);const save=async()=>{if(!draft)return;try{await api(`/technical-visits/${visit.id}/devices${draft.id?`/${draft.id}`:''}`,json(draft.id?'PUT':'POST',draft));setDraft(undefined);await load()}catch(error){onMessage(String(error))}};const remove=async(id:string)=>{try{await api(`/technical-visits/${visit.id}/devices/${id}`,{method:'DELETE'});await load()}catch(error){onMessage(String(error))}};return <Detail title="Equipamentos envolvidos" onAdd={()=>setDraft({...base,deviceId:'',deviceName:'',deviceCategory:'',role:'inspected',notes:''})}>{draft&&<div className="detail-editor form-grid"><Field label="Equipamento *"><select value={draft.deviceId} onChange={e=>setDraft({...draft,deviceId:e.target.value})}><option value="">Selecione</option>{devices.map(device=><option key={device.id} value={device.id}>{device.name}</option>)}</select></Field><Field label="Papel *"><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{Object.entries(deviceRoles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Observações"><input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><EditorActions onCancel={()=>setDraft(undefined)} onSave={save}/></div>}{list.length===0?<Empty>Nenhum equipamento relacionado.</Empty>:<table><thead><tr><th>Equipamento</th><th>Papel</th><th>Observações</th><th></th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td>{item.deviceName}<small>{item.deviceCategory}</small></td><td>{deviceRoles[item.role]}</td><td>{item.notes||'—'}</td><Actions onEdit={()=>setDraft({...item})} onDelete={()=>void remove(item.id)}/></tr>)}</tbody></table>}</Detail>}

function Services({visit,onMessage}:Omit<Props,'section'>){const[list,setList]=useState<VisitServiceItem[]>([]);const[devices,setDevices]=useState<Device[]>([]);const[draft,setDraft]=useState<VisitServiceItem>();const load=async()=>{setList(items(await api<{items:VisitServiceItem[]}>(`/technical-visits/${visit.id}/services`)));setDevices(items(await api<{items:Device[]}>(`/devices?project_id=${visit.projectId}`)))};useEffect(()=>{void load().catch(error=>onMessage(String(error)))},[visit.id]);const save=async()=>{if(!draft)return;try{await api(`/technical-visits/${visit.id}/services${draft.id?`/${draft.id}`:''}`,json(draft.id?'PUT':'POST',draft));setDraft(undefined);await load()}catch(error){onMessage(String(error))}};const remove=async(id:string)=>{await api(`/technical-visits/${visit.id}/services/${id}`,{method:'DELETE'});await load()};return <Detail title="Serviços executados" onAdd={()=>setDraft({...base,description:'',category:'',deviceId:'',deviceName:'',performedAt:'',technician:visit.responsibleTechnician,notes:'',order:list.length+1})}>{draft&&<div className="detail-editor form-grid"><Field label="Descrição *"><input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><Field label="Categoria"><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></Field><Field label="Equipamento"><select value={draft.deviceId} onChange={e=>setDraft({...draft,deviceId:e.target.value})}><option value="">Nenhum</option>{devices.map(device=><option key={device.id} value={device.id}>{device.name}</option>)}</select></Field><Field label="Horário"><input type="datetime-local" value={draft.performedAt.slice(0,16)} onChange={e=>setDraft({...draft,performedAt:e.target.value})}/></Field><Field label="Técnico"><input value={draft.technician} onChange={e=>setDraft({...draft,technician:e.target.value})}/></Field><Field label="Ordem"><input type="number" min="0" value={draft.order} onChange={e=>setDraft({...draft,order:Number(e.target.value)})}/></Field><Field label="Observações"><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><EditorActions onCancel={()=>setDraft(undefined)} onSave={save}/></div>}{list.length===0?<Empty>Nenhum serviço registrado.</Empty>:<table><thead><tr><th>#</th><th>Descrição</th><th>Equipamento</th><th>Técnico</th><th></th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td>{item.order}</td><td>{item.description}<small>{item.category||item.notes}</small></td><td>{item.deviceName||'—'}</td><td>{item.technician||'—'}</td><Actions onEdit={()=>setDraft({...item})} onDelete={()=>void remove(item.id)}/></tr>)}</tbody></table>}</Detail>}

function Checklist({visit,onMessage}:Omit<Props,'section'>){const[list,setList]=useState<VisitChecklistItem[]>([]);const[draft,setDraft]=useState<VisitChecklistItem>();const load=async()=>setList(items(await api<{items:VisitChecklistItem[]}>(`/technical-visits/${visit.id}/checklist`)));useEffect(()=>{void load().catch(error=>onMessage(String(error)))},[visit.id]);const saveItem=async(item:VisitChecklistItem)=>{try{await api(`/technical-visits/${visit.id}/checklist${item.id?`/${item.id}`:''}`,json(item.id?'PUT':'POST',item));setDraft(undefined);await load()}catch(error){onMessage(String(error))}};const remove=async(id:string)=>{await api(`/technical-visits/${visit.id}/checklist/${id}`,{method:'DELETE'});await load()};return <Detail title="Checklist" onAdd={()=>setDraft({...base,text:'',status:'pending',notes:'',order:list.length+1})}>{draft&&<div className="detail-editor form-grid"><Field label="Item *"><input value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></Field><Field label="Status"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="pending">Pendente</option><option value="completed">Concluído</option><option value="not_applicable">Não aplicável</option></select></Field><Field label="Ordem"><input type="number" min="0" value={draft.order} onChange={e=>setDraft({...draft,order:Number(e.target.value)})}/></Field><Field label="Observação"><input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><EditorActions onCancel={()=>setDraft(undefined)} onSave={()=>saveItem(draft)}/></div>}{list.length===0?<Empty>Checklist vazio.</Empty>:<div className="checklist-list">{list.map(item=><div key={item.id}><input type="checkbox" checked={item.status==='completed'} onChange={()=>void saveItem({...item,status:item.status==='completed'?'pending':'completed'})}/><span className={item.status==='completed'?'done':''}>{item.text}<small>{item.notes}</small></span><button type="button" onClick={()=>setDraft({...item})}>Editar</button><ConfirmButton message="Excluir item?" onConfirm={()=>void remove(item.id)}>Excluir</ConfirmButton></div>)}</div>}</Detail>}

function Materials({visit,onMessage}:Omit<Props,'section'>){const[list,setList]=useState<VisitMaterialItem[]>([]);const[draft,setDraft]=useState<VisitMaterialItem>();const load=async()=>setList(items(await api<{items:VisitMaterialItem[]}>(`/technical-visits/${visit.id}/materials`)));useEffect(()=>{void load().catch(error=>onMessage(String(error)))},[visit.id]);const save=async()=>{if(!draft)return;try{await api(`/technical-visits/${visit.id}/materials${draft.id?`/${draft.id}`:''}`,json(draft.id?'PUT':'POST',draft));setDraft(undefined);await load()}catch(error){onMessage(String(error))}};const remove=async(id:string)=>{await api(`/technical-visits/${visit.id}/materials/${id}`,{method:'DELETE'});await load()};return <Detail title="Materiais utilizados" onAdd={()=>setDraft({...base,quantity:1,unit:'un',description:'',brand:'',model:'',notes:''})}>{draft&&<div className="detail-editor form-grid"><Field label="Quantidade *"><input type="number" min="0.01" step="any" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:Number(e.target.value)})}/></Field><Field label="Unidade *"><input value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/></Field><Field label="Descrição *"><input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><Field label="Marca"><input value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})}/></Field><Field label="Modelo"><input value={draft.model} onChange={e=>setDraft({...draft,model:e.target.value})}/></Field><Field label="Observação"><input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><EditorActions onCancel={()=>setDraft(undefined)} onSave={save}/></div>}{list.length===0?<Empty>Nenhum material registrado.</Empty>:<table><thead><tr><th>Quantidade</th><th>Descrição</th><th>Marca / Modelo</th><th></th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td>{item.quantity} {item.unit}</td><td>{item.description}<small>{item.notes}</small></td><td>{[item.brand,item.model].filter(Boolean).join(' · ')||'—'}</td><Actions onEdit={()=>setDraft({...item})} onDelete={()=>void remove(item.id)}/></tr>)}</tbody></table>}</Detail>}

function Pending({visit,onMessage}:Omit<Props,'section'>){const[list,setList]=useState<VisitPendingItem[]>([]);const[draft,setDraft]=useState<VisitPendingItem>();const load=async()=>setList(items(await api<{items:VisitPendingItem[]}>(`/technical-visits/${visit.id}/pending-items`)));useEffect(()=>{void load().catch(error=>onMessage(String(error)))},[visit.id]);const save=async()=>{if(!draft)return;try{await api(`/technical-visits/${visit.id}/pending-items${draft.id?`/${draft.id}`:''}`,json(draft.id?'PUT':'POST',draft));setDraft(undefined);await load()}catch(error){onMessage(String(error))}};const remove=async(id:string)=>{await api(`/technical-visits/${visit.id}/pending-items/${id}`,{method:'DELETE'});await load()};return <Detail title="Pendências" onAdd={()=>setDraft({...base,description:'',priority:'normal',responsible:'',dueAt:'',status:'pending'})}>{draft&&<div className="detail-editor form-grid"><Field label="Descrição *"><input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><Field label="Prioridade"><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{Object.entries(priorities).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Responsável"><input value={draft.responsible} onChange={e=>setDraft({...draft,responsible:e.target.value})}/></Field><Field label="Prazo"><input type="date" value={draft.dueAt.slice(0,10)} onChange={e=>setDraft({...draft,dueAt:e.target.value})}/></Field><Field label="Status"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(pendingStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><EditorActions onCancel={()=>setDraft(undefined)} onSave={save}/></div>}{list.length===0?<Empty>Nenhuma pendência registrada.</Empty>:<table><thead><tr><th>Descrição</th><th>Prioridade</th><th>Responsável / Prazo</th><th>Status</th><th></th></tr></thead><tbody>{list.map(item=><tr key={item.id}><td>{item.description}</td><td><span className={`priority priority-${item.priority}`}>{priorities[item.priority]}</span></td><td>{item.responsible||'—'}<small>{item.dueAt||'Sem prazo'}</small></td><td>{pendingStatuses[item.status]}</td><Actions onEdit={()=>setDraft({...item})} onDelete={()=>void remove(item.id)}/></tr>)}</tbody></table>}</Detail>}

function Detail({title,onAdd,children}:{title:string;onAdd:()=>void;children:ReactNode}){return <section className="visit-detail"><div className="section-heading"><h3>{title}</h3><button type="button" onClick={onAdd}>+ Adicionar</button></div><div className="table-scroll">{children}</div></section>}
function EditorActions({onCancel,onSave}:{onCancel:()=>void;onSave:()=>void|Promise<void>}){return <div className="form-actions"><button type="button" onClick={onCancel}>Cancelar</button><button type="button" className="primary" onClick={()=>void onSave()}>Salvar item</button></div>}
function Actions({onEdit,onDelete}:{onEdit:()=>void;onDelete:()=>void}){return <td className="row-actions"><button type="button" onClick={onEdit}>Editar</button><ConfirmButton message="Excluir item?" onConfirm={onDelete}>Excluir</ConfirmButton></td>}
