import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api, items, json } from '../api'
import { Client, Project, TechnicalVisit } from '../types'
import { ConfirmButton, Empty, Field, Modal, Notice, PageHeader, Panel, Status } from '../components'
import VisitDetails, { DetailSection } from './VisitDetails'

export const visitTypeLabels:Record<string,string>={installation:'Instalação',preventive_maintenance:'Manutenção preventiva',corrective_maintenance:'Manutenção corretiva',inspection:'Vistoria',diagnosis:'Diagnóstico',network_expansion:'Expansão de rede',cctv:'CFTV',cabling:'Cabeamento',fiber_optic:'Fibra óptica',wifi:'Wi-Fi',telephony:'Telefonia',migration:'Migração',device_replacement:'Substituição de equipamento',configuration:'Configuração',documentation:'Documentação',other:'Outro'}
export const resultLabels:Record<string,string>={'':'—',resolved:'Resolvido',partially_resolved:'Parcialmente resolvido',not_resolved:'Não resolvido',waiting_material:'Aguardando material',waiting_customer:'Aguardando cliente',requires_return:'Necessita retorno',no_fault_found:'Sem defeito encontrado'}
const statusLabels:Record<string,string>={draft:'Rascunho',scheduled:'Agendada',in_progress:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}
type Section='attendance'|'report'|'notes'|DetailSection

const emptyVisit=(projectId=''):TechnicalVisit=>({id:'',projectId,clientId:'',clientName:'',projectName:'',protocol:'',title:'',visitType:'corrective_maintenance',status:'draft',result:'',scheduledAt:new Date().toISOString().slice(0,16),startedAt:'',finishedAt:'',durationMinutes:0,responsibleTechnician:'',requester:'',localContact:'',requestDescription:'',initialSituation:'',diagnosis:'',workSummary:'',recommendations:'',pendingSummary:'',customerNotes:'',internalNotes:'',requiresReturn:false,returnReason:'',suggestedReturnAt:'',createdAt:'',updatedAt:''})
const displayDate=(value:string)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—'
const duration=(minutes:number)=>minutes?`${Math.floor(minutes/60)}h${String(minutes%60).padStart(2,'0')}`:'—'

export default function VisitsPage({initialProjectId='' }:{initialProjectId?:string}) {
  const [visits,setVisits]=useState<TechnicalVisit[]>([])
  const [clients,setClients]=useState<Client[]>([])
  const [projects,setProjects]=useState<Project[]>([])
  const [form,setForm]=useState<TechnicalVisit>()
  const [section,setSection]=useState<Section>('attendance')
  const [message,setMessage]=useState('')
  const [filters,setFilters]=useState({q:'',clientId:'',projectId:initialProjectId,status:'',result:'',dateFrom:'',dateTo:''})
  const availableProjects=useMemo(()=>filters.clientId?projects.filter(project=>project.clientId===filters.clientId):projects,[projects,filters.clientId])
  const formProjects=useMemo(()=>form?.clientId?projects.filter(project=>project.clientId===form.clientId):projects,[projects,form?.clientId])
  const load=async(next=filters)=>{const params=new URLSearchParams();if(next.q)params.set('q',next.q);if(next.clientId)params.set('client_id',next.clientId);if(next.projectId)params.set('project_id',next.projectId);if(next.status)params.set('status',next.status);if(next.result)params.set('result',next.result);if(next.dateFrom)params.set('date_from',next.dateFrom);if(next.dateTo)params.set('date_to',next.dateTo);try{setVisits(items(await api<{items:TechnicalVisit[]}>(`/technical-visits?${params}`)))}catch(error){setMessage(String(error))}}
  useEffect(()=>{void Promise.all([api<{items:Client[]}>('/clients').then(value=>setClients(items(value))),api<{items:Project[]}>('/projects').then(value=>setProjects(items(value)))])},[])
  useEffect(()=>{const next={...filters,projectId:initialProjectId};setFilters(next);void load(next)},[initialProjectId])
  const newVisit=()=>{const project=projects.find(value=>value.id===filters.projectId);setSection('attendance');setForm({...emptyVisit(filters.projectId),clientId:project?.clientId??filters.clientId})}
  const edit=(visit:TechnicalVisit)=>{setSection('attendance');setForm({...visit})}
  const save=async(event:FormEvent)=>{event.preventDefault();if(!form)return;try{if(form.id){await api<TechnicalVisit>(`/technical-visits/${form.id}`,json('PUT',form))}else{await api<TechnicalVisit>('/technical-visits',json('POST',form))};setForm(undefined);setMessage('Visita técnica salva.');await load()}catch(error){setMessage(String(error))}}
  const remove=async(id:string)=>{try{await api(`/technical-visits/${id}`,{method:'DELETE'});setMessage('Visita técnica excluída.');await load()}catch(error){setMessage(String(error))}}
  const setClient=(clientId:string)=>setForm(form?{...form,clientId,projectId:projects.some(project=>project.id===form.projectId&&project.clientId===clientId)?form.projectId:''}:form)
  return <>
    <PageHeader eyebrow="ATENDIMENTO" title="Visitas técnicas" description="Registre e acompanhe os atendimentos por cliente e projeto." actions={<button className="primary" onClick={newVisit}>+ Nova visita</button>}/>
    <Notice message={message} onClose={()=>setMessage('')}/>
    <Panel className="visit-filters"><div className="filter-grid"><input aria-label="Pesquisar visitas" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="Protocolo, título, técnico ou diagnóstico"/><select aria-label="Filtrar cliente" value={filters.clientId} onChange={e=>setFilters({...filters,clientId:e.target.value,projectId:''})}><option value="">Todos os clientes</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select><select aria-label="Filtrar projeto" value={filters.projectId} onChange={e=>setFilters({...filters,projectId:e.target.value})}><option value="">Todos os projetos</option>{availableProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><select aria-label="Filtrar status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar resultado" value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}><option value="">Todos os resultados</option>{Object.entries(resultLabels).filter(([value])=>value).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Field label="De"><input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/></Field><Field label="Até"><input type="date" value={filters.dateTo} onChange={e=>setFilters({...filters,dateTo:e.target.value})}/></Field><button onClick={()=>void load()}>Aplicar filtros</button></div></Panel>
    <Panel title={`Visitas (${visits.length})`}>{visits.length===0?<Empty>Nenhuma visita encontrada.</Empty>:<div className="table-scroll"><table><thead><tr><th>Protocolo</th><th>Data</th><th>Cliente / Projeto</th><th>Tipo</th><th>Técnico</th><th>Resultado</th><th>Status</th><th></th></tr></thead><tbody>{visits.map(visit=><tr key={visit.id}><td><button className="link-button" onClick={()=>edit(visit)}>{visit.protocol}</button><small>{visit.title}</small></td><td>{displayDate(visit.scheduledAt)}</td><td>{visit.clientName}<small>{visit.projectName}</small></td><td>{visitTypeLabels[visit.visitType]}</td><td>{visit.responsibleTechnician||'—'}</td><td>{resultLabels[visit.result]}</td><td><Status value={visit.status}/>{visit.requiresReturn&&<small className="return-flag">RETORNO NECESSÁRIO</small>}</td><td className="row-actions"><button onClick={()=>edit(visit)}>Abrir</button><ConfirmButton message={`Excluir ${visit.protocol}?`} onConfirm={()=>void remove(visit.id)}>Excluir</ConfirmButton></td></tr>)}</tbody></table></div>}</Panel>
    {form&&<Modal title={form.id?`${form.protocol} · ${form.title}`:'Nova visita técnica'} onClose={()=>setForm(undefined)} wide><form onSubmit={save} className="visit-form"><div className="form-tabs" role="tablist"><button type="button" className={section==='attendance'?'active':''} onClick={()=>setSection('attendance')}>1. Atendimento</button><button type="button" className={section==='report'?'active':''} onClick={()=>setSection('report')}>2. Relato técnico</button><button type="button" className={section==='devices'?'active':''} disabled={!form.id} onClick={()=>setSection('devices')}>3. Equipamentos</button><button type="button" className={section==='services'?'active':''} disabled={!form.id} onClick={()=>setSection('services')}>4. Serviços</button><button type="button" className={section==='checklist'?'active':''} disabled={!form.id} onClick={()=>setSection('checklist')}>5. Checklist</button><button type="button" className={section==='materials'?'active':''} disabled={!form.id} onClick={()=>setSection('materials')}>6. Materiais</button><button type="button" className={section==='pending'?'active':''} disabled={!form.id} onClick={()=>setSection('pending')}>7. Pendências</button><button type="button" className={section==='notes'?'active':''} onClick={()=>setSection('notes')}>8. Resultado</button></div>
      {section==='attendance'&&<div className="form-grid"><Field label="Cliente *"><select required value={form.clientId} onChange={e=>setClient(e.target.value)}><option value="">Selecione</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Projeto *"><select required value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value})}><option value="">Selecione</option>{formProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><Field label="Título *"><input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Tipo de atendimento *"><select required value={form.visitType} onChange={e=>setForm({...form,visitType:e.target.value})}>{Object.entries(visitTypeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Data e hora *"><input required type="datetime-local" value={form.scheduledAt.slice(0,16)} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Início"><input type="datetime-local" value={form.startedAt.slice(0,16)} onChange={e=>setForm({...form,startedAt:e.target.value})}/></Field><Field label="Fim"><input type="datetime-local" value={form.finishedAt.slice(0,16)} onChange={e=>setForm({...form,finishedAt:e.target.value})}/></Field><Field label="Técnico responsável"><input value={form.responsibleTechnician} onChange={e=>setForm({...form,responsibleTechnician:e.target.value})}/></Field><Field label="Duração calculada"><input readOnly value={duration(form.durationMinutes)}/></Field><Field label="Solicitante"><input value={form.requester} onChange={e=>setForm({...form,requester:e.target.value})}/></Field><Field label="Contato no local"><input value={form.localContact} onChange={e=>setForm({...form,localContact:e.target.value})}/></Field></div>}
      {section==='report'&&<div className="form-grid one"><Field label="Descrição da solicitação"><textarea value={form.requestDescription} onChange={e=>setForm({...form,requestDescription:e.target.value})}/></Field><Field label="Situação encontrada"><textarea value={form.initialSituation} onChange={e=>setForm({...form,initialSituation:e.target.value})}/></Field><Field label="Diagnóstico"><textarea value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})}/></Field><Field label="Resumo dos serviços executados"><textarea value={form.workSummary} onChange={e=>setForm({...form,workSummary:e.target.value})}/></Field><Field label="Recomendações"><textarea value={form.recommendations} onChange={e=>setForm({...form,recommendations:e.target.value})}/></Field><Field label="Resumo de pendências"><textarea value={form.pendingSummary} onChange={e=>setForm({...form,pendingSummary:e.target.value})}/></Field></div>}
      {section==='notes'&&<div className="form-grid"><Field label="Resultado"><select value={form.result} onChange={e=>setForm({...form,result:e.target.value})}>{Object.entries(resultLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Necessita retorno"><select value={form.requiresReturn?'yes':'no'} onChange={e=>setForm({...form,requiresReturn:e.target.value==='yes'})}><option value="no">Não</option><option value="yes">Sim</option></select></Field>{form.requiresReturn&&<><Field label="Motivo do retorno"><input value={form.returnReason} onChange={e=>setForm({...form,returnReason:e.target.value})}/></Field><Field label="Data sugerida"><input type="datetime-local" value={form.suggestedReturnAt.slice(0,16)} onChange={e=>setForm({...form,suggestedReturnAt:e.target.value})}/></Field></>}<Field label="Observações para o cliente"><textarea value={form.customerNotes} onChange={e=>setForm({...form,customerNotes:e.target.value})}/></Field><Field label="Observações internas (não públicas)"><textarea value={form.internalNotes} onChange={e=>setForm({...form,internalNotes:e.target.value})}/></Field></div>}
      {form.id&&(['devices','services','checklist','materials','pending'] as DetailSection[]).includes(section as DetailSection)&&<VisitDetails visit={form} section={section as DetailSection} onMessage={setMessage}/>} 
      <div className="form-actions"><button type="button" onClick={()=>setForm(undefined)}>Cancelar</button><button className="primary">Salvar visita</button></div>
    </form></Modal>}
  </>
}
